name: Ballerina Client CI Pipeline - DEVELOPMENT

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
jobs:
  ballerina_client_ci_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Install dependencies
        run: bal build
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Install Pact Mock Server
        run: |
          # Install the Pact Mock Server
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.10/pact-2.0.10-linux-x86_64.tar.gz
          tar xzf pact-2.0.10-linux-x86_64.tar.gz
          cd pact/bin
          ./pact-mock-service --consumer $PACT_CONSUMER --provider $PACT_PROVIDER --port $PACT_SERVER_PORT --pact-dir $PACT_DIR --log $LOG_PATH --log-level $LOG_LEVEL &
          cd ..
        env:
          PACT_CONSUMER: "BallerinaClient"
          PACT_PROVIDER: "BallerinaProvider"
          PACT_SERVER_PORT: 1234
          PACT_DIR: "/home/runner/work/BallerinaClient/BallerinaClient/tests"
          LOG_PATH: "/home/runner/work/BallerinaClient/BallerinaClient/tests/ballerina_mock_service.log"
          LOG_LEVEL: DEBUG

      - name: Run Ballerina tests & generate Pact file
        run: bal test --groups pact

      - name: Publish Pact file to Pact Broker
        run: |
          # Publish the Pact file to the Pact Broker with basic authentication
          cd pact/bin
          pwd
          ./pact-broker publish /home/runner/work/BallerinaClient/BallerinaClient/tests \
            --broker-base-url $PACT_BROKER_URL \
            --broker-username $PACT_BROKER_USERNAME \
            --broker-password $PACT_BROKER_PASSWORD \
            --consumer-app-version=0.1.0 \
            --auto-detect-version-properties=true \
            --tag-with-git-branch=true
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}

      - name: Can I deploy to development environment
        run: |
          cd pact/bin
          ./pact-broker can-i-deploy -a=BallerinaClient -b=$PACT_BROKER_URL --branch=main --broker-username=$PACT_BROKER_USERNAME --broker-password=$PACT_BROKER_PASSWORD --to-environment=dev
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
  
      - name: Deploy to Dev
        run: |
          echo "deployed"
        
      - name: Update pact broker
        run: |
          cd pact/bin
          ./pact-broker record-deployment --environment=dev -a=BallerinaClient --version=0.1.0  --broker-username=$PACT_BROKER_USERNAME --broker-password=$PACT_BROKER_PASSWORD -b=$PACT_BROKER_URL
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
